name: Generate Sitemap

on:
  push:
    branches:
      - main  # Ganti dengan nama branch utama Anda jika berbeda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Atur sesuai dengan versi Node.js yang Anda inginkan

    - name: Install dependencies
      run: npm install

    - name: Generate sitemap.xml
      run: node generate_sitemap.js

    - name: Commit and push sitemap.xml
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add sitemap.xml
        git commit -m 'Generate sitemap.xml'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
